[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rominf-stanza-fi-processor-pos"
version = "1.8.0"

[project.optional-dependencies]
default = [
    "rominf-stanza-fi-processor-pos-tdt-charlm==1.8.0"
]
