[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rominf-stanza-fi-model-pos"
version = "1.8.0"
dependencies = [
    "rominf-stanza-fi-model-pos-tdt-charlm==1.8.0"
]
