[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rominf-stanza-fi-processor-tokenize-ftb"
version = "1.8.0"

[tool.setuptools.packages.find]
where = ["data"]
